name: capturist
adopt-info: capturist-part

type: app
base: core24
grade: stable
confinement: strict
platforms:
  amd64:
    build-on:
      - amd64

parts:
  capturist-part:
    plugin: dump
    build-snaps:
      - node/24/stable
      - rustup/latest/stable
    build-packages:
      - libssl-dev
    stage-packages:
      - libnotify-bin
    stage:
      - -usr/lib/*/libicuio.so*
      - -usr/lib/*/libicutu.so*
      - -usr/lib/*/libicutest.so*
    source: .
    parse-info:
      - me.ariyadey.capturist.metainfo.xml
    # language=Bash
    override-build: |
      set -eu

      if [ ! -f "capturist.deb" ]; then
          echo "--- No pre-built deb found, building from source... ---"
          rustup default stable
          npm ci --no-audit --no-fund
          npm run tauri build -- --config src-tauri/tauri.snap.conf.json
          mv src-tauri/target/release/bundle/deb/*.deb capturist.deb
      fi

      dpkg -x capturist.deb "$SNAPCRAFT_PART_INSTALL"/
      desktop_file="$SNAPCRAFT_PART_INSTALL/usr/share/applications/Capturist.desktop"
      icon_path="/usr/share/icons/hicolor/128x128/apps/capturist.png"
      sed -i -e "s|Icon=capturist|Icon=$icon_path|g" "$desktop_file"

apps:
  capturist:
    command: usr/bin/capturist
    desktop: usr/share/applications/Capturist.desktop
    extensions:
      # The gnome extension already includes
      # [ desktop, desktop-legacy, gsettings, opengl, wayland, x11, mount-observe, calendar-service ]
      - gnome
    plugs:
      - network
      - network-status
      - password-manager-service
      - single-instance-plug
    slots:
      - single-instance-slot

plugs:
  single-instance-plug:
    interface: dbus
    bus: session
    name: org.me_ariyadey_capturist.SingleInstance

slots:
  single-instance-slot:
    interface: dbus
    bus: session
    name: org.me_ariyadey_capturist.SingleInstance

layout:
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.1:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1
